name: Setup Google Cloud container registry mirror
description: Use Google Cloud container registry mirror instead of pulling images from docker hub

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        config-inline: |
          debug = true
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
