name: Upload docs
description: Upload documentation

inputs:
  docs_bucket_sa:
    description: "Documentation bucket service account"
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Setup gcloud credentials
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
          project_id: prod-econo-cm
          service_account_key: ${{ inputs.docs_bucket_sa }}
          export_default_credentials: true  
    
    - name: Upload docs
      shell: bash
      run: |
        echo Creating a temporary directory for docs content
        mkdir -p _docs
        echo Searching for readme.md file and coping to temporary directory
        find -iname readme.md -exec cp {} ./_docs \;
        echo Listing docs directory content
        ls -al ./_docs
        echo Removing existing docs for ${{ github.event.repository.name }}
        gsutil -m rm -r gs://prod-econo-cm_docs/${{ github.event.repository.name }} 2> /dev/null || true
        echo Uploading docs to Google Cloud Storage for ${{ github.event.repository.name }}
        gsutil -m cp -r _docs gs://prod-econo-cm_docs/${{ github.event.repository.name }}
        echo Removing temporary docs directory
        rm -rf _docs
        
