name: Upload docs
description: Upload documentation

inputs:
  docs_bucket_sa:
    description: "Documentation bucket service account"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup gcloud credentials
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        project_id: prod-econo-cm
        service_account_key: ${{ inputs.docs_bucket_sa }}
        export_default_credentials: true

    - uses: actions/checkout@v3
      with:
        repository: e-conomic/github-actions
        path: _github-actions

    - name: Prepare docs
      shell: bash
      run: |
        mkdir -p ./_docs-prepare

        echo "Copying README.md file from the root directory"
        find -maxdepth 1 -iname readme.md -exec cp {} ./_docs-prepare \;

        if [[ -d ./docs ]]
        then
            echo "'docs' directory exists, prepearing for upload"
            cp -vR ./docs/** ./_docs-prepare/
        fi

        echo "Listing docs prepared directory structure"
        ls -alR ./_docs-prepare

    - uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Prepare docs for validation
      shell: bash
      run: |
        cp -vR ./_docs-prepare/** ./_github-actions/upload-docs/docusaurus/docs/

# - name: Install packages
#   shell: bash
#   working-directory: ./_github-actions/upload-docs/docusaurus
#   run: |
#     npm ci

# - name: Build docs
#   shell: bash
#   working-directory: ./_github-actions/upload-docs/docusaurus
#   run: |
#     npm run build

    - name: Get helper names into env variables
      shell: bash
      id: service_name
      run: echo ::set-output name=service_name::${GITHUB_REPOSITORY##*/}

    - name: Upload docs
      shell: bash
      run: |
        echo "Removing existing docs for ${{ steps.service_name.outputs.service_name }}"
        gsutil -m rm -r gs://prod-econo-cm_docs/${{ steps.service_name.outputs.service_name }} 2>&1 || true

        echo "Uploading docs to Google Cloud Storage for ${{ steps.service_name.outputs.service_name }}"
        gsutil -m cp -r ./_docs-prepare gs://prod-econo-cm_docs/${{ steps.service_name.outputs.service_name }}
