name: Polaris SAST
description: Run Polaris static application security test

inputs:
  api_url:
    description: "Polaris API URL"
    required: true
  access_token:
    description: "Polaris access token"
    required: true
    
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        POLARIS_ACCESS_TOKEN: ${{ inputs.access_token }}
        GIT_BRANCH: ${{ github.ref_name }}
      run: |
        ls -al
        echo Current directory: $(pwd)
        wget -q ${{ inputs.api_url }}/api/tools/polaris_cli-linux64.zip
        unzip -j polaris_cli-linux64.zip -d /tmp
        /tmp/polaris analyze --upload-local-config
        unlink polaris_cli-linux64.zip
        rm -rf /tmp/polaris_cli-linux64
