name: Polaris SAST
description: Run Polaris static application security test

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        GIT_BRANCH: ${{ github.ref_name }}
      run: |
        ls -al
        echo Current directory: $(pwd)
        wget -q ${{ secrets.POLARIS_API_URL }}/api/tools/polaris_cli-linux64.zip
        unzip -j polaris_cli-linux64.zip -d /tmp
        /tmp/polaris analyze --upload-local-config
        unlink polaris_cli-linux64.zip
        rm -rf /tmp/polaris_cli-linux64
