name: Polaris SAST
description: Run Polaris static application security test
shell: bash

inputs:
  directory_path:
    description: "Full or a relative path of the directory where the action should run"
    required: true

run: |
  ALLOW_FAILURE=false
  POLARIS_API_URL=${{ secrets.POLARIS_API_URL }}
  POLARIS_ACCESS_TOKEN=${{ secrets.POLARIS_ACCESS_TOKEN }}
  GIT_BRANCH=${{ github.ref_name }}
  ls
  pwd
  initial_dir=$(pwd)
  cd ${{inputs.directory_path}}
  ls
  pwd
  wget -q ${{ secrets.POLARIS_API_URL }}/api/tools/polaris_cli-linux64.zip
  unzip -j polaris_cli-linux64.zip -d /tmp
  /tmp/polaris analyze --upload-local-config
  ls
  pwd
  unlink polaris_cli-linux64.zip
  rm -rf /tmp/polaris_cli-linux64
  cd $initial_dir
  ls
  pwd
