name: Polaris SAST
description: Run Polaris static application security test

inputs:
  api_url:
    description: "Polaris API URL"
    required: true
  access_token:
    description: "Polaris access token"
    required: true
    
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        POLARIS_ACCESS_TOKEN: ${{ inputs.access_token }}
        GIT_BRANCH: ${{ github.ref_name }}
      run: |
        echo Current directory: $(pwd)
        echo Downloading Polaris CLI
        wget -q ${{ inputs.api_url }}/api/tools/polaris_cli-linux64.zip
        echo Unzipping Polaris CLI
        unzip -j polaris_cli-linux64.zip -d /tmp/polari_cli
        echo Removing archive
        unlink polaris_cli-linux64.zip
        echo Starting analysis
        /tmp/polari_cli/polaris analyze --upload-local-config
        echo Removing Polaris CLI
        rm -rf /tmp/polari_cli
