name: Mergebot

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:

jobs:
  auto_merge:
    name: Auto merge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: e-conomic/mergebot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          semver_match: minor
